const GET_DOGS = 'GET_DOGS';
const GET_DOGS_BY_NAME = 'GET_DOGS_BY_NAME';
const GET_DOG = 'GET_DOG';
const POST_DOG = 'POST_DOG';
const ERROR = 'ERROR';
const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS';


export {GET_DOG, GET_DOGS_BY_NAME, GET_DOGS, POST_DOG, GET_TEMPERAMENTS, ERROR}